frutas = ['laranja', 'maça', 'pera', 'banana', 'kiwi', 'maça','banana']
print(frutas.count('maça'))
print(frutas.count('tangerina'))
print(frutas.index('banana'))
print(frutas.index('banana', 4))
frutas.reverse()
print(frutas)
frutas.append('uva')
print(frutas)
frutas.sort()
print(frutas)
print(frutas.pop())
print(frutas)
