M1=str(input("Digite o primeiro Horário: "))
M2=str(input("Digite o segundo Horário: "))
h1,min1=M1.split("h")
h2,min2=M2.split("h")
horario1=int(h1)
minuto1=int(min1)
horario2=int(h2)
minuto2=int(min2)
minutos_passados=horario2*60+minuto2-(horario1*60+minuto1)
print("Passaram-se",minutos_passados,"minutos")